const portfolioData = [
	{
		heading: "Care-Full - Full Stack App",
		link: "https://github.com/SchoolOfCode/final-project_front-end-team-con-cat-enate-room-7/blob/main/README-NEW.md",
		deployedApp: "https://care-full.netlify.app/",
		id: "careFullApp",
		src: "./Images/care-full.png",
		alt: "Giraffe Support",
		text: "This was our final project at School of Code. In a group of 6, we set out to design and create a full stack app which would allow the user to better care for their pet. I worked on everything involved in the project, UX/UI, front end, back end, styling, auth0 and testing. This was a fantastic challenge, I have learnt so much throughout this project and I am incredibly proud of what we have achieved.",
	},
	{
		heading: "Giraffe Support - Full Stack App",
		link: "https://github.com/rachelalk/Frontend---Giraffe-Support-Ticketing-System/blob/main/README.md",
		deployedApp: "https://giraffe-support.netlify.app/",
		id: "giraffeSupportImage",
		src: "./Images/giraffeSupport.png",
		alt: "Giraffe Support",
		text: "Week 9 project. In a team of 4 we were given 4.5 days to solve aproblem that bootcampers face. We were to go through the whole UX/UI process, work in an agile way, build our MVP from scratch including frontend and backend and prepare a presentation in this time. We created a ticketing system to handle help requests.",
	},
	{
		heading: "Weather API using Typescript",
		link: "https://github.com/rachelalk/Weather-App-Typescript",
		deployedApp: "https://panda-weather.netlify.app/",
		id: "Weather",
		src: "./Images/weatherAPI.png",
		alt: "Weather API",
		text: "Week 12 hackathon. After learning Typescript for only two days, we were tasked with using a weather API to create a react app, using Typescript. This was a real challenge as we were only just getting to grips with the language. Using an interface to define the types expected for all properties of an API response was particularly challenging.",
	},
	{
		heading: "Restaurant API Hackathon",
		link: "https://github.com/rachelalk/restaurant-hackathon",
		deployedApp: "https://thai-takeout.netlify.app/",
		id: "restaurantAPI",
		src: "./Images/restaurant_api.png",
		alt: "restaurant",
		text: "Post bootcamp hackathon. In a team of 3 we were tasked with creating a restaurant app using the Spoonacular API. The app had a number of requirements including producing a minimum of 2 lo-fi wireframes, some form of testing, we opted for Cypress end to end, and an app consisting of 3 pages: a homepage, menu page including modals about the food and a basket which can only be accessed with a minimum of 2 items selected.",
	},
	{
		heading: "Authentication using Auth0",
		link: "https://github.com/rachelalk/Auth0",
		deployedApp: "https://fox-fix.netlify.app/",
		id: "Auth0",
		src: "./Images/Auth0.png",
		alt: "Auth0 authentication",
		text: "Week 10 hackathon. We were tasked with using the docs to figure out how to use Auth0 for both front and back end and then use it in a simple app.",
	},
	{
		heading: "Cat API - React",
		link: "https://github.com/rachelalk/Cats-API-with-React---Agile-working",
		deployedApp: "https://soc-cat-collector.netlify.app/",
		id: "catApiImage",
		src: "./Images/CatAPI.png",
		alt: "Cat API",
		text: "Week 8 hackathon project. We used Create React App to create a full stack React app. We spent time planning, went through the ideation and planning process and created an app that allows you to browse cat breeds, save favourites and clear your list.",
	},
	{
		heading: "Books API - React",
		link: "https://github.com/rachelalk/Books-API-With-React",
		deployedApp: "https://soc-books-api.netlify.app/",
		id: "booksApiImage",
		src: "./Images/booksAPI.png",
		alt: "Books API",
		text: "Solo project, completed in an afternoon following week 8 in order to practice skills learnt throughout the week.",
	},
	{
		heading: "To Do List - React",
		link: "https://github.com/rachelalk/React-To-Do-List",
		deployedApp: "https://soc-to-do-list.netlify.app",
		id: "toDoListImage",
		src: "./Images/toDoList.png",
		alt: "To do list",
		text: "Week 7 hackathon. This was our first project with react. We had some trouble with this during the hackathon and didn't manage to get things working so I went back to it the following day and completed the task. Please see the read me on my github for full details.",
	},
	{
		heading: "Personality Quiz - UseReducer",
		link: "https://github.com/rachelalk/useReducer-Buffy-Personality-Quiz",
		deployedApp: "https://buffy-quiz.netlify.app/",
		id: "buffyPersonalityQuiz",
		src: "./Images/buffy.png",
		alt: "Buffy personality quiz",
		text: "During week 8 we were introduced to useReducer and were tasked with refactoring code into a useReducer and then to create a personality quiz of our choice and style it within react.",
	},
];

export default portfolioData;
